"""Claude-driven autonomous conflict resolution.

Renders a prompt template, spawns ``claude -p``, streams its output to the
console, enforces a timeout, and verifies the post-conditions (branch pushed,
PR opened, AI label attached) using the existing GitHub helpers.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from releasy.termlog import console

from releasy.config import Config
from releasy.git_ops import (
    is_operation_in_progress,
    run_git,
)
from releasy.github_ops import PRInfo


# What kind of conflicted git operation Claude is being asked to drive to
# completion. Picks the prompt template (``ai_resolve.prompt_file`` for
# cherry-picks, ``ai_resolve.merge_prompt_file`` for merges) and shapes
# the placeholders rendered into it.
OperationKind = Literal["cherry-pick", "merge"]


@dataclass
class AIResolveContext:
    port_branch: str
    base_branch: str
    # The PR most relevant to interpreting the conflict:
    # - cherry-pick: the upstream PR being ported (source of the commits).
    # - merge:       the upstream source PR the rebase branch ports — the
    #                conflict is between its changes and the moved-on
    #                base branch, so its intent is what Claude must
    #                preserve.
    source_pr: PRInfo
    conflict_files: list[str] = field(default_factory=list)
    # SHA of the port branch tip BEFORE the conflicting operation was
    # attempted. Used to verify Claude actually committed something, and
    # to reset to a known-good state on failure.
    start_sha: str | None = None
    # Which kind of conflict Claude is resolving. Selects the prompt
    # template and tweaks the postcondition narrative.
    operation: OperationKind = "cherry-pick"
    # Merge-only context: the URL of the rebase PR whose branch is being
    # kept current. Rendered into the merge prompt so Claude can name it
    # in commit messages / log lines if it wants. Ignored for cherry-pick.
    rebase_pr_url: str | None = None


@dataclass
class AIResolveResult:
    success: bool
    iterations: int | None = None
    error: str | None = None
    timed_out: bool = False
    new_head: str | None = None  # branch tip after Claude's commit
    # Total USD cost reported by Claude across every attempt of this
    # resolve invocation (sum of ``total_cost_usd`` from each
    # ``result``-typed event in the stream-json transcript, including
    # transient-API-error retries). ``None`` when Claude reported no cost
    # at all (e.g. failed before producing a result event).
    cost_usd: float | None = None
    # When Claude reported ``MISSING_PREREQS: <url1> <url2>`` in its
    # output (followed by ``UNRESOLVED``), these are the discovered PR
    # URLs and the one-line REASON. Empty list / None when the run was
    # not classified as a missing-prereq situation. Always paired with
    # ``success=False`` and a non-None ``error`` ("claude reported
    # MISSING_PREREQS"); the pipeline reads ``missing_prereq_prs`` to
    # branch into detection-only labelling or auto-recovery.
    missing_prereq_prs: list[str] = field(default_factory=list)
    missing_prereq_note: str | None = None


# ---------------------------------------------------------------------------
# Build wrapper script
# ---------------------------------------------------------------------------
#
# Claude Code's Bash tool matcher refuses compound commands (subshells,
# `&&`, `;`, `bash -c '…'`). The user's build_command is intrinsically
# multi-step (`cd build` + `cmake …` + `ninja`) and its output is too
# large to fit in a single Bash tool result. We solve both problems at
# once by writing the build commands to a wrapper script inside the repo
# (`.releasy/build.sh`) that internally tees full output to
# `.releasy/build.log`. Claude then only needs to run the single
# command  `bash .releasy/build.sh`, and can `Read` the log on failure.

_BUILD_DIR = ".releasy"
_BUILD_SCRIPT = f"{_BUILD_DIR}/build.sh"
_BUILD_LOG = f"{_BUILD_DIR}/build.log"


def _write_build_script(repo_path: Path, build_command: str) -> None:
    """Materialise the build wrapper inside the repo.

    Overwrites any previous copy so config changes take effect.
    """
    target = repo_path / _BUILD_SCRIPT
    target.parent.mkdir(parents=True, exist_ok=True)
    body = build_command.rstrip() + "\n"
    script = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by RelEasy. Do not edit by hand — regenerated\n"
        "# on every AI-resolve invocation from ai_resolve.build_command.\n"
        "set -euo pipefail\n"
        "cd \"$(git rev-parse --show-toplevel)\"\n"
        f"mkdir -p {_BUILD_DIR}\n"
        f"exec > >(tee {_BUILD_LOG}) 2>&1\n"
        "echo \"[releasy] build started at $(date -u +%FT%TZ)\"\n"
        "(\n"
        f"{body}"
        ")\n"
        "echo \"[releasy] build finished at $(date -u +%FT%TZ)\"\n"
    )
    target.write_text(script, encoding="utf-8")
    target.chmod(0o755)

    gitignore = repo_path / _BUILD_DIR / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("*\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Prompt rendering
# ---------------------------------------------------------------------------


def _resolve_prompt_template(config: Config, ctx: AIResolveContext) -> Path:
    """Pick the prompt file path for ``ctx.operation`` and resolve it.

    Cherry-pick uses ``ai_resolve.prompt_file``; merge uses
    ``ai_resolve.merge_prompt_file`` so the two flows can have distinct
    instructions (`git cherry-pick --continue` vs `git commit --no-edit`,
    different framing of "what's in progress") while sharing the same
    placeholder vocabulary.
    """
    if ctx.operation == "merge":
        raw = config.ai_resolve.merge_prompt_file
    else:
        raw = config.ai_resolve.prompt_file
    prompt_path = Path(raw)
    if not prompt_path.is_absolute():
        prompt_path = (config.repo_dir / prompt_path).resolve()
    return prompt_path


def _render_prompt(config: Config, repo_path: Path, ctx: AIResolveContext) -> str:
    """Load the prompt template and fill in placeholders."""
    prompt_path = _resolve_prompt_template(config, ctx)

    if not prompt_path.exists():
        which = (
            "ai_resolve.merge_prompt_file" if ctx.operation == "merge"
            else "ai_resolve.prompt_file"
        )
        raise FileNotFoundError(
            f"AI prompt template not found: {prompt_path}. "
            f"Set {which} in config."
        )

    template = prompt_path.read_text(encoding="utf-8")

    from releasy.github_ops import get_origin_repo_slug
    repo_slug = get_origin_repo_slug(config) or "<unknown>"

    conflict_files_md = "\n".join(f"- `{f}`" for f in ctx.conflict_files) or "- (none)"

    body = (ctx.source_pr.body or "").strip()
    if not body:
        body = "_(empty)_"
    elif len(body) > 4000:
        body = body[:4000] + "\n\n_(truncated)_"

    # SHA Claude can use to inspect the EXACT diff being applied (cherry-pick
    # of a merge commit uses the first-parent diff, which is what `git show -m
    # --first-parent` prints). For open PRs we fall back to head_sha so Claude
    # still has a concrete ref; the prompt also tells it to use `gh pr diff`
    # as a cross-check.
    source_pr_merge_sha = (
        ctx.source_pr.merge_commit_sha or ctx.source_pr.head_sha or ""
    )

    # Origin remote / default branch — referenced by the prereq-detection
    # section of the cherry-pick prompt so commands stay literal-copy
    # ready (not "git log -S … origin/master" hard-coded when the user
    # configured a different remote_name).
    origin_remote_name = config.origin.remote_name
    # The "default" branch on origin to search prereq history against.
    # We don't have a config knob for this today (target_branch is the
    # *port target*, which is exactly the branch where the prereq is
    # missing — not the right thing to search). Default to ``master``,
    # the convention for the upstream-mirror repos RelEasy targets.
    origin_branch_default = "master"

    if config.upstream is not None:
        upstream_remote_name = config.upstream.remote_name
        upstream_branch = config.upstream.branch
        upstream_fetch_section = (
            "Also search the upstream remote (fetch it first):\n\n"
            "```bash\n"
            f"git fetch {upstream_remote_name} {upstream_branch} --depth=500\n"
            f"git log -S '<identifier>' --oneline {upstream_remote_name}/"
            f"{upstream_branch} -- <file>\n"
            "```\n"
        )
    else:
        upstream_remote_name = ""
        upstream_branch = ""
        upstream_fetch_section = (
            "_(no upstream remote is configured; only the origin history "
            "above is searched)_\n"
        )

    placeholders = {
        "repo_slug": repo_slug,
        "cwd": str(repo_path),
        "port_branch": ctx.port_branch,
        "base_branch": ctx.base_branch,
        "source_pr_url": ctx.source_pr.url,
        "source_pr_title": ctx.source_pr.title,
        "source_pr_number": str(ctx.source_pr.number),
        "source_pr_body": body,
        "source_pr_merge_sha": source_pr_merge_sha,
        "conflict_files": conflict_files_md,
        "build_command": config.ai_resolve.build_command,
        "build_script": _BUILD_SCRIPT,
        "build_log": _BUILD_LOG,
        "max_iterations": str(config.ai_resolve.max_iterations),
        "label": config.ai_resolve.label,
        # Merge-only — rendered as a literal placeholder for cherry-pick
        # prompts that don't reference it (no-op there). For merge prompts
        # this lets Claude link the rebase PR in narration if helpful.
        "rebase_pr_url": ctx.rebase_pr_url or "",
        # Prereq-detection placeholders (cherry-pick prompt only — the
        # merge prompt doesn't reference them, so empty values are safe).
        "origin_remote_name": origin_remote_name,
        "origin_branch": origin_branch_default,
        "upstream_remote_name": upstream_remote_name,
        "upstream_branch": upstream_branch,
        "upstream_fetch_section": upstream_fetch_section,
    }

    def _replace(match: re.Match[str]) -> str:
        key = match.group(1)
        return placeholders.get(key, match.group(0))

    return re.sub(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", _replace, template)


# ---------------------------------------------------------------------------
# Claude invocation
# ---------------------------------------------------------------------------


def _build_claude_argv(config: Config, prompt: str) -> list[str]:
    cmd = [
        config.ai_resolve.command,
        "-p", prompt,
        "--output-format", "stream-json",
        "--verbose",
    ]
    if config.ai_resolve.allowed_tools:
        cmd += ["--allowedTools", ",".join(config.ai_resolve.allowed_tools)]
    cmd += list(config.ai_resolve.extra_args)
    return cmd


def _fmt_elapsed(seconds: float) -> str:
    s = int(seconds)
    if s < 60:
        return f"{s}s"
    if s < 3600:
        return f"{s // 60}m{s % 60:02d}s"
    return f"{s // 3600}h{(s % 3600) // 60:02d}m"


def _truncate(text: str, n: int = 120) -> str:
    text = text.strip().replace("\n", " ⏎ ")
    return text if len(text) <= n else text[: n - 1] + "…"


def _render_event(line: str, start: float) -> str | None:
    """Turn one stream-json event into a human-readable status line.

    Returns ``None`` when the event has nothing user-visible to report.
    """
    try:
        ev = json.loads(line)
    except json.JSONDecodeError:
        stripped = line.strip()
        if not stripped:
            return None
        return f"[dim]│[/dim] {stripped}"

    elapsed = _fmt_elapsed(time.monotonic() - start)
    etype = ev.get("type")

    if etype == "system":
        sub = ev.get("subtype", "")
        model = ev.get("model") or ""
        if sub == "init":
            return f"[dim]│ [{elapsed}][/dim] [magenta]session start[/magenta] {model}".rstrip()
        return None

    if etype == "assistant":
        msg = ev.get("message") or {}
        parts = []
        for block in msg.get("content") or []:
            btype = block.get("type")
            if btype == "text":
                txt = _truncate(block.get("text", ""))
                if txt:
                    parts.append(f"[dim]│ [{elapsed}][/dim] [cyan]💬[/cyan] {txt}")
            elif btype == "thinking":
                txt = _truncate(block.get("thinking", ""), 80)
                if txt:
                    parts.append(f"[dim]│ [{elapsed}] 🧠 {txt}[/dim]")
            elif btype == "tool_use":
                name = block.get("name", "tool")
                inp = block.get("input") or {}
                summary = ""
                if name == "Bash":
                    summary = _truncate(str(inp.get("command", "")), 100)
                elif name in ("Read", "Write", "Edit"):
                    summary = str(inp.get("file_path") or inp.get("path") or "")
                elif name == "Glob":
                    summary = str(inp.get("pattern") or inp.get("glob_pattern") or "")
                elif name == "Grep":
                    summary = _truncate(str(inp.get("pattern", "")), 80)
                else:
                    keys = ", ".join(list(inp)[:3])
                    summary = f"({keys})" if keys else ""
                line_str = f"[dim]│ [{elapsed}][/dim] [yellow]🔧 {name}[/yellow]"
                if summary:
                    line_str += f" {summary}"
                parts.append(line_str)
        return "\n".join(parts) if parts else None

    if etype == "user":
        msg = ev.get("message") or {}
        for block in msg.get("content") or []:
            if block.get("type") == "tool_result":
                content = block.get("content")
                if isinstance(content, list):
                    text = " ".join(
                        c.get("text", "") for c in content if isinstance(c, dict)
                    )
                else:
                    text = str(content or "")
                is_err = block.get("is_error")
                marker = "[red]✗[/red]" if is_err else "[green]✓[/green]"
                summary = _truncate(text, 100)
                if not summary:
                    return None
                return f"[dim]│ [{elapsed}][/dim] {marker} [dim]{summary}[/dim]"
        return None

    if etype == "result":
        sub = ev.get("subtype", "")
        cost = ev.get("total_cost_usd")
        turns = ev.get("num_turns")
        bits = [f"result={sub}"]
        if turns is not None:
            bits.append(f"turns={turns}")
        if cost is not None:
            bits.append(f"cost=${cost:.3f}")
        return f"[dim]│ [{elapsed}] {' '.join(bits)}[/dim]"

    return None


def _kill_proc_tree(proc: subprocess.Popen) -> None:
    """SIGTERM (then SIGKILL) the entire process group of ``proc``.

    Claude spawns child tools (ninja, gcc, gh, …); without targeting the
    whole group those survive after we kill claude itself. ``proc`` is
    started with ``start_new_session=True`` so it owns its own process
    group whose pgid equals the child pid.
    """
    if proc.poll() is not None:
        return
    try:
        pgid = os.getpgid(proc.pid)
    except (ProcessLookupError, OSError):
        return
    try:
        os.killpg(pgid, signal.SIGTERM)
    except (ProcessLookupError, OSError):
        pass
    try:
        proc.wait(timeout=5)
        return
    except subprocess.TimeoutExpired:
        pass
    try:
        os.killpg(pgid, signal.SIGKILL)
    except (ProcessLookupError, OSError):
        pass
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass


def _spawn_claude(
    argv: list[str], repo_path: Path, timeout: int,
) -> tuple[int, str, bool]:
    """Run claude as a subprocess, streaming stdout/stderr to the console.

    Parses Claude's stream-json events and pretty-prints each tool call,
    message, and tool result. Emits a heartbeat when claude is quiet so
    the user can tell it's still working. Ctrl-C kills the whole claude
    process group (claude + ninja + whatever else it spawned) and
    re-raises ``KeyboardInterrupt``.

    Returns (exit_code, combined_output, timed_out).
    """
    console.print(
        f"    [dim]$ {shlex.join(argv[:2])} <prompt…> "
        f"{shlex.join(argv[3:])}[/dim]"
    )
    console.print("    [dim](press Ctrl-C to abort claude)[/dim]")

    env = os.environ.copy()

    # start_new_session=True puts claude in its own process group so:
    #   1. it does NOT receive the terminal's Ctrl-C (we control it),
    #   2. we can kill the entire tree (claude + nested tools) at once.
    proc = subprocess.Popen(
        argv,
        cwd=repo_path,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        start_new_session=True,
    )

    collected: list[str] = []
    start = time.monotonic()
    last_output = start
    timed_out = False
    interrupted = False
    stop_heartbeat = threading.Event()

    def _heartbeat() -> None:
        idle_threshold = 30.0
        while not stop_heartbeat.wait(15.0):
            idle = time.monotonic() - last_output
            if idle >= idle_threshold:
                console.print(
                    f"    [dim]│ [{_fmt_elapsed(time.monotonic() - start)}] "
                    f"…still working (idle {int(idle)}s)[/dim]"
                )

    hb = threading.Thread(target=_heartbeat, daemon=True)
    hb.start()

    try:
        assert proc.stdout is not None
        while True:
            if (time.monotonic() - start) > timeout:
                timed_out = True
                break
            try:
                line = proc.stdout.readline()
            except KeyboardInterrupt:
                interrupted = True
                break
            if not line:
                if proc.poll() is not None:
                    break
                continue
            collected.append(line)
            last_output = time.monotonic()
            rendered = _render_event(line, start)
            if rendered:
                console.print(f"    {rendered}")
    except KeyboardInterrupt:
        interrupted = True
    except Exception as exc:
        collected.append(f"[runner] error streaming claude output: {exc}\n")
    finally:
        stop_heartbeat.set()
        if proc.poll() is None:
            reason = (
                "interrupted by user"
                if interrupted
                else f"timed out after {timeout}s"
                if timed_out
                else "stream ended; cleaning up"
            )
            console.print(
                f"    [yellow]✗ killing claude ({reason})…[/yellow]"
            )
            _kill_proc_tree(proc)

    if interrupted:
        raise KeyboardInterrupt

    exit_code = proc.returncode if proc.returncode is not None else -1
    return exit_code, "".join(collected), timed_out


# ---------------------------------------------------------------------------
# Post-condition verification
# ---------------------------------------------------------------------------


def _extract_assistant_text(output: str) -> str:
    """Pull all assistant text out of a stream-json transcript.

    Falls back to the raw output when nothing parses as JSON.
    """
    chunks: list[str] = []
    parsed_any = False
    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            chunks.append(line)
            continue
        parsed_any = True
        if ev.get("type") == "assistant":
            for block in (ev.get("message") or {}).get("content") or []:
                if block.get("type") == "text":
                    chunks.append(block.get("text", ""))
        elif ev.get("type") == "result":
            res = ev.get("result")
            if isinstance(res, str):
                chunks.append(res)
    if not parsed_any:
        return output
    return "\n".join(chunks)


# Heuristics for transient Anthropic streaming-API failures that abort
# the turn before Claude can do any real work. We retry on these; we do
# NOT retry on real resolver errors (build failed, UNRESOLVED, etc.).
_TRANSIENT_API_ERROR_RES = [
    re.compile(r"API Error:\s*Stream idle timeout", re.IGNORECASE),
    re.compile(r"API Error:\s*Overloaded", re.IGNORECASE),
    re.compile(r"API Error:\s*5\d\d", re.IGNORECASE),
    re.compile(r"API Error:\s*Connection (?:reset|closed)", re.IGNORECASE),
    re.compile(r"API Error:\s*Request timed out", re.IGNORECASE),
    re.compile(r"API Error:\s*ECONNRESET", re.IGNORECASE),
    re.compile(r"API Error:\s*fetch failed", re.IGNORECASE),
    re.compile(r"partial response received", re.IGNORECASE),
]


def _find_transient_api_error(output: str) -> str | None:
    """Return a short human-readable reason if the turn was aborted by a
    transient Anthropic API error, else ``None``.

    We look both in raw lines and in the assistant text extracted from
    the stream-json transcript.
    """
    assistant = _extract_assistant_text(output)
    for haystack in (assistant, output):
        for pat in _TRANSIENT_API_ERROR_RES:
            m = pat.search(haystack)
            if m:
                return m.group(0)
    return None


def _extract_cost_usd(output: str) -> float | None:
    """Sum ``total_cost_usd`` across every ``result`` event in the transcript.

    Claude emits one ``result``-typed stream-json event per session
    summarising the run. When ``resolve_with_claude`` retries after a
    transient API error, each attempt produces its own result event and
    the costs need to be added together to reflect the full bill for the
    invocation. Returns ``None`` if no usable cost field was found.
    """
    total: float | None = None
    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            continue
        if ev.get("type") != "result":
            continue
        cost = ev.get("total_cost_usd")
        if isinstance(cost, (int, float)):
            total = (total or 0.0) + float(cost)
    return total


_MISSING_PREREQS_RE = re.compile(
    r"^MISSING_PREREQS:\s*(.+?)\s*$",
    re.MULTILINE,
)
_REASON_RE = re.compile(r"^REASON:\s*(.+?)\s*$", re.MULTILINE)
# A token that *looks like* a GitHub PR URL — broad on purpose so we
# accept variants like ``https://github.com/owner/repo/pull/123#whatever``
# without dropping them. Validation happens downstream via
# ``parse_pr_url``; the parser's job is just to peel them off the
# MISSING_PREREQS line.
_PR_URL_TOKEN_RE = re.compile(
    r"https?://github\.com/[^/\s]+/[^/\s]+/pull/\d+[\w/#?=&.\-]*",
    re.IGNORECASE,
)


def _parse_missing_prereqs(output: str) -> tuple[list[str], str | None]:
    """Extract MISSING_PREREQS PR URLs (and the one-line REASON) from the
    transcript.

    The prompt's contract: Claude prints ``MISSING_PREREQS: url1 url2 ...``
    on one line and ``REASON: <one-liner>`` on the next, followed by
    ``UNRESOLVED`` on its own line. We accept any whitespace separator
    between URLs (space, tab, comma) and trim trailing punctuation.

    Returns ``([], None)`` when no MISSING_PREREQS line was emitted.
    """
    text = _extract_assistant_text(output)
    urls: list[str] = []
    seen: set[str] = set()
    # Walk every MISSING_PREREQS occurrence — there should normally only
    # be one, but if Claude restated it (e.g. once mid-narration and once
    # at the tail) we union them rather than picking arbitrarily.
    for m in _MISSING_PREREQS_RE.finditer(text):
        for tok in _PR_URL_TOKEN_RE.finditer(m.group(1)):
            url = tok.group(0).rstrip(".,;:)]\"'")
            if url not in seen:
                seen.add(url)
                urls.append(url)
    if not urls:
        return [], None
    reason_match = _REASON_RE.search(text)
    reason = reason_match.group(1).strip() if reason_match else None
    return urls, reason


def _count_iterations(output: str) -> int | None:
    """Best-effort: count how many build attempts Claude ran.

    Looks for patterns in its own narration. Returns None when unknown.
    """
    text = _extract_assistant_text(output)
    patterns = [
        r"build attempt[s]?:?\s*(\d+)",
        r"iteration\s*(\d+)\s*/\s*\d+",
    ]
    best: int | None = None
    for pat in patterns:
        for m in re.finditer(pat, text, re.IGNORECASE):
            try:
                n = int(m.group(1))
            except ValueError:
                continue
            best = n if best is None else max(best, n)
    return best


def _verify_postconditions(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> tuple[bool, str | None, str | None]:
    """Step-mode check: cherry-pick fully concluded, tree clean, HEAD moved.

    RelEasy itself owns push / PR / label, so we only verify Claude's
    local-repo invariants:

    - no cherry-pick / merge / rebase still in progress,
    - working tree is clean (no unstaged conflict-resolution leftovers),
    - the port branch advanced past ``ctx.start_sha`` (i.e. at least one
      commit was actually made).

    Returns ``(ok, new_head_sha, error_message)``.
    """
    if is_operation_in_progress(repo_path):
        return False, None, (
            "cherry-pick/merge/rebase still in progress after claude exited"
        )

    # Ignore untracked files: scratch dirs the AI agent leaves behind
    # (e.g. tmp/, build artifacts) don't affect the cherry-pick's
    # correctness. We only care about unstaged/staged changes to tracked
    # files, which would indicate unfinished conflict resolution.
    porc = run_git(
        ["status", "--porcelain", "--untracked-files=no"],
        repo_path, check=False,
    )
    if porc.stdout.strip():
        files = ", ".join(
            line[3:] for line in porc.stdout.splitlines()[:5]
        )
        return False, None, f"working tree not clean: {files}"

    head = run_git(["rev-parse", "--verify", "HEAD"], repo_path, check=False)
    if head.returncode != 0:
        return False, None, "could not read HEAD"
    new_head = head.stdout.strip()

    if ctx.start_sha and new_head == ctx.start_sha:
        return False, new_head, (
            "no new commits — cherry-pick was not concluded"
        )

    return True, new_head, None


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def resolve_with_claude(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> AIResolveResult:
    """Render the prompt, run claude, and verify post-conditions."""
    if shutil.which(config.ai_resolve.command) is None:
        return AIResolveResult(
            success=False,
            error=f"'{config.ai_resolve.command}' not found on PATH",
        )

    try:
        _write_build_script(repo_path, config.ai_resolve.build_command)
    except OSError as exc:
        return AIResolveResult(
            success=False, error=f"could not write build wrapper: {exc}",
        )

    try:
        prompt = _render_prompt(config, repo_path, ctx)
    except FileNotFoundError as exc:
        return AIResolveResult(success=False, error=str(exc))

    argv = _build_claude_argv(config, prompt)

    console.print(
        f"    [magenta]\U0001f916 invoking {config.ai_resolve.command} "
        f"(timeout {config.ai_resolve.timeout_seconds}s, "
        f"max {config.ai_resolve.max_iterations} build attempts, "
        f"up to {config.ai_resolve.api_retries} API-error retries)[/magenta]"
    )

    max_attempts = max(1, config.ai_resolve.api_retries + 1)
    backoff = max(0, config.ai_resolve.api_retry_backoff_seconds)

    last_exit_code = -1
    last_output = ""
    last_timed_out = False
    # Cost accrues across retries — each attempt is a separate billed
    # turn even when only the last one succeeded. ``last_output`` only
    # carries the most recent attempt's transcript, so we aggregate the
    # per-attempt cost as we go.
    cost_usd_total: float | None = None

    for attempt in range(1, max_attempts + 1):
        if attempt > 1:
            console.print(
                f"    [yellow]↻ retrying claude after transient API error "
                f"(attempt {attempt}/{max_attempts}, sleeping {backoff}s)"
                f"[/yellow]"
            )
            try:
                time.sleep(backoff)
            except KeyboardInterrupt:
                raise

        exit_code, output, timed_out = _spawn_claude(
            argv, repo_path, config.ai_resolve.timeout_seconds,
        )
        last_exit_code, last_output, last_timed_out = exit_code, output, timed_out

        attempt_cost = _extract_cost_usd(output)
        if attempt_cost is not None:
            cost_usd_total = (cost_usd_total or 0.0) + attempt_cost

        if timed_out:
            break

        transient = _find_transient_api_error(output)
        if transient and exit_code != 0 and attempt < max_attempts:
            console.print(
                f"    [yellow]⚠ transient API error: {transient}"
                f" — will retry[/yellow]"
            )
            continue

        break

    exit_code = last_exit_code
    output = last_output
    timed_out = last_timed_out

    iterations = _count_iterations(output)
    assistant_text = _extract_assistant_text(output)

    if timed_out:
        return AIResolveResult(
            success=False, timed_out=True, iterations=iterations,
            error=f"claude timed out after {config.ai_resolve.timeout_seconds}s",
            cost_usd=cost_usd_total,
        )

    tail_lines = assistant_text.strip().splitlines()[-40:] if assistant_text.strip() else []
    tail_str = "\n".join(tail_lines)

    # Check MISSING_PREREQS *before* the generic UNRESOLVED check: the prompt
    # contract is "MISSING_PREREQS: ... ; REASON: ... ; UNRESOLVED" together,
    # so an UNRESOLVED tail line by itself doesn't disambiguate the two.
    # Scan the full transcript (not just the tail) because Claude sometimes
    # emits the structured marker mid-narration before its closing summary.
    missing_prereq_prs, missing_prereq_note = _parse_missing_prereqs(output)
    if missing_prereq_prs:
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported MISSING_PREREQS",
            cost_usd=cost_usd_total,
            missing_prereq_prs=missing_prereq_prs,
            missing_prereq_note=missing_prereq_note,
        )
    if any(line.strip() == "UNRESOLVED" for line in tail_lines):
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported UNRESOLVED",
            cost_usd=cost_usd_total,
        )
    if any(line.strip() == "BUILD FAILED" for line in tail_lines):
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported BUILD FAILED",
            cost_usd=cost_usd_total,
        )

    if exit_code != 0:
        transient = _find_transient_api_error(output)
        suffix = (
            f" (transient API error after {max_attempts} attempt(s): {transient})"
            if transient
            else ""
        )
        return AIResolveResult(
            success=False, iterations=iterations,
            error=f"claude exited with code {exit_code}{suffix}\n{tail_str}",
            cost_usd=cost_usd_total,
        )

    ok, new_head, err = _verify_postconditions(config, repo_path, ctx)
    if not ok:
        return AIResolveResult(
            success=False, iterations=iterations, new_head=new_head, error=err,
            cost_usd=cost_usd_total,
        )

    return AIResolveResult(
        success=True, iterations=iterations, new_head=new_head, error=err,
        cost_usd=cost_usd_total,
    )


# ---------------------------------------------------------------------------
# High-level wrapper used by every caller (cherry-pick + merge resolvers)
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Stand-alone text generation (changelog entry synthesis)
# ---------------------------------------------------------------------------


@dataclass
class AITextResult:
    """Outcome of a one-shot Claude text-generation call.

    Used by callers (e.g. CHANGELOG entry synthesis) that just want a
    short text back without any tool use or post-condition checks.
    """
    success: bool
    text: str | None = None
    error: str | None = None
    timed_out: bool = False
    cost_usd: float | None = None


def _resolve_changelog_prompt_path(config: Config) -> Path:
    """Resolve the changelog-synthesis prompt template path.

    Same convention as :func:`_resolve_prompt_template`: relative paths
    are anchored at ``config.repo_dir`` so per-project overrides drop
    into a ``prompts/`` directory next to ``config.yaml``.
    """
    raw = config.ai_changelog.prompt_file
    p = Path(raw)
    if not p.is_absolute():
        p = (config.repo_dir / p).resolve()
    return p


def synthesize_text(
    config: Config,
    prompt: str,
    *,
    label: str,
    timeout_seconds: int,
    command: str,
) -> AITextResult:
    """Run Claude on ``prompt`` and return the assistant's reply text.

    No tools are made available — this is pure text generation. Cost is
    extracted from the stream-json transcript when present; the call is
    routed through :func:`_spawn_claude` so the user sees the same
    streaming heartbeat / Ctrl-C semantics as the conflict resolver.

    The CWD passed to Claude is a throwaway temp dir so it has nowhere
    interesting to write into even if the model misinterprets the
    no-tools constraint.
    """
    if shutil.which(command) is None:
        return AITextResult(
            success=False,
            error=f"'{command}' not found on PATH",
        )

    argv = [
        command,
        "-p", prompt,
        "--output-format", "stream-json",
        "--verbose",
        # Explicit empty allowed-tools list keeps Claude in pure
        # text-generation mode for this call.
        "--allowedTools", "",
    ]

    console.print(
        f"    [magenta]\U0001f916 synthesizing text via "
        f"{command} for [cyan]{label}[/cyan] "
        f"(timeout {timeout_seconds}s)[/magenta]"
    )

    import tempfile

    with tempfile.TemporaryDirectory(prefix="releasy-ai-text-") as td:
        try:
            exit_code, output, timed_out = _spawn_claude(
                argv, Path(td), timeout_seconds,
            )
        except KeyboardInterrupt:
            raise

    cost = _extract_cost_usd(output)

    if timed_out:
        return AITextResult(
            success=False, timed_out=True, cost_usd=cost,
            error=f"claude timed out after {timeout_seconds}s",
        )

    if exit_code != 0:
        transient = _find_transient_api_error(output)
        suffix = f" ({transient})" if transient else ""
        return AITextResult(
            success=False, cost_usd=cost,
            error=f"claude exited with code {exit_code}{suffix}",
        )

    text = _extract_assistant_text(output).strip()
    if not text:
        return AITextResult(
            success=False, cost_usd=cost,
            error="claude returned empty output",
        )

    return AITextResult(success=True, text=text, cost_usd=cost)


def synthesize_changelog_entry(
    config: Config,
    *,
    unit_label: str,
    pr_blocks: str,
    n_prs: int,
    base_branch: str,
    source_repo: str,
) -> AITextResult:
    """Render the changelog-synthesis prompt and ask Claude to fill it.

    Caller (``releasy.pipeline``) is responsible for building
    ``pr_blocks`` — a markdown chunk containing each source PR's
    title + body in cherry-pick order, already truncated to a
    reasonable size — so the prompt template stays decoupled from the
    project-specific PR-info dataclass.
    """
    prompt_path = _resolve_changelog_prompt_path(config)
    if not prompt_path.exists():
        return AITextResult(
            success=False,
            error=(
                "changelog-synthesis prompt template not found: "
                f"{prompt_path}. Set ai_changelog.prompt_file in config "
                "to point at a real file (or copy the bundled "
                "prompts/synthesize_changelog.md alongside config.yaml)."
            ),
        )

    template = prompt_path.read_text(encoding="utf-8")
    placeholders = {
        "n_prs": str(n_prs),
        "base_branch": base_branch,
        "source_repo": source_repo,
        "pr_blocks": pr_blocks,
    }

    def _replace(match: re.Match[str]) -> str:
        key = match.group(1)
        return placeholders.get(key, match.group(0))

    rendered = re.sub(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", _replace, template)

    return synthesize_text(
        config, rendered,
        label=unit_label,
        timeout_seconds=config.ai_changelog.timeout_seconds,
        command=config.ai_changelog.command,
    )


def attempt_ai_resolve(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> AIResolveResult:
    """Render the prompt, run claude, and clean up on failure.

    Wraps :func:`resolve_with_claude` with the cleanup contract every
    caller needs: on a failed resolve the in-progress git operation
    (cherry-pick / merge / rebase) is aborted and HEAD is hard-reset to
    ``ctx.start_sha`` so the working tree is back to a known-good state.
    Callers (the cherry-pick step, the PR-merge updater) only need to
    decide *what to do* on success/failure, not *how to clean up*.

    If ``ctx.start_sha`` isn't set the helper fills it from the current
    HEAD before invoking Claude, so PR-conflict-resolution callers don't
    have to remember to capture it themselves.
    """
    if ctx.start_sha is None:
        head = run_git(["rev-parse", "--verify", "HEAD"], repo_path, check=False)
        ctx.start_sha = head.stdout.strip() if head.returncode == 0 else None

    result = resolve_with_claude(config, repo_path, ctx)

    if result.success:
        return result

    # Reset the worktree so the caller can decide what to do next without
    # tripping over half-baked merge / cherry-pick state.
    if is_operation_in_progress(repo_path):
        run_git(["cherry-pick", "--abort"], repo_path, check=False)
        run_git(["merge", "--abort"], repo_path, check=False)
        run_git(["rebase", "--abort"], repo_path, check=False)
    if ctx.start_sha:
        run_git(["reset", "--hard", ctx.start_sha], repo_path, check=False)

    return result
