"""Claude-driven autonomous conflict resolution.

Renders a prompt template, spawns ``claude -p``, streams its output to the
console, enforces a timeout, and verifies the post-conditions (branch pushed,
PR opened, AI label attached) using the existing GitHub helpers.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

from rich.console import Console

from releasy.config import Config
from releasy.git_ops import (
    is_operation_in_progress,
    run_git,
)
from releasy.github_ops import PRInfo

console = Console()


@dataclass
class AIResolveContext:
    port_branch: str
    base_branch: str
    source_pr: PRInfo
    conflict_files: list[str] = field(default_factory=list)
    # SHA of the port branch tip BEFORE the conflicting cherry-pick was
    # attempted. Used to verify Claude actually committed something.
    start_sha: str | None = None


@dataclass
class AIResolveResult:
    success: bool
    iterations: int | None = None
    error: str | None = None
    timed_out: bool = False
    new_head: str | None = None  # branch tip after Claude's commit


# ---------------------------------------------------------------------------
# Build wrapper script
# ---------------------------------------------------------------------------
#
# Claude Code's Bash tool matcher refuses compound commands (subshells,
# `&&`, `;`, `bash -c '…'`). The user's build_command is intrinsically
# multi-step (`cd build` + `cmake …` + `ninja`) and its output is too
# large to fit in a single Bash tool result. We solve both problems at
# once by writing the build commands to a wrapper script inside the repo
# (`.releasy/build.sh`) that internally tees full output to
# `.releasy/build.log`. Claude then only needs to run the single
# command  `bash .releasy/build.sh`, and can `Read` the log on failure.

_BUILD_DIR = ".releasy"
_BUILD_SCRIPT = f"{_BUILD_DIR}/build.sh"
_BUILD_LOG = f"{_BUILD_DIR}/build.log"


def _write_build_script(repo_path: Path, build_command: str) -> None:
    """Materialise the build wrapper inside the repo.

    Overwrites any previous copy so config changes take effect.
    """
    target = repo_path / _BUILD_SCRIPT
    target.parent.mkdir(parents=True, exist_ok=True)
    body = build_command.rstrip() + "\n"
    script = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by RelEasy. Do not edit by hand — regenerated\n"
        "# on every AI-resolve invocation from ai_resolve.build_command.\n"
        "set -euo pipefail\n"
        "cd \"$(git rev-parse --show-toplevel)\"\n"
        f"mkdir -p {_BUILD_DIR}\n"
        f"exec > >(tee {_BUILD_LOG}) 2>&1\n"
        "echo \"[releasy] build started at $(date -u +%FT%TZ)\"\n"
        "(\n"
        f"{body}"
        ")\n"
        "echo \"[releasy] build finished at $(date -u +%FT%TZ)\"\n"
    )
    target.write_text(script, encoding="utf-8")
    target.chmod(0o755)

    gitignore = repo_path / _BUILD_DIR / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("*\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Prompt rendering
# ---------------------------------------------------------------------------


def _render_prompt(config: Config, repo_path: Path, ctx: AIResolveContext) -> str:
    """Load the prompt template and fill in placeholders."""
    prompt_path = Path(config.ai_resolve.prompt_file)
    if not prompt_path.is_absolute():
        prompt_path = (config.repo_dir / prompt_path).resolve()

    if not prompt_path.exists():
        raise FileNotFoundError(
            f"AI prompt template not found: {prompt_path}. "
            f"Set ai_resolve.prompt_file in config."
        )

    template = prompt_path.read_text(encoding="utf-8")

    from releasy.github_ops import get_origin_repo_slug
    repo_slug = get_origin_repo_slug(config) or "<unknown>"

    conflict_files_md = "\n".join(f"- `{f}`" for f in ctx.conflict_files) or "- (none)"

    body = (ctx.source_pr.body or "").strip()
    if not body:
        body = "_(empty)_"
    elif len(body) > 4000:
        body = body[:4000] + "\n\n_(truncated)_"

    placeholders = {
        "repo_slug": repo_slug,
        "cwd": str(repo_path),
        "port_branch": ctx.port_branch,
        "base_branch": ctx.base_branch,
        "source_pr_url": ctx.source_pr.url,
        "source_pr_title": ctx.source_pr.title,
        "source_pr_number": str(ctx.source_pr.number),
        "source_pr_body": body,
        "conflict_files": conflict_files_md,
        "build_command": config.ai_resolve.build_command,
        "build_script": _BUILD_SCRIPT,
        "build_log": _BUILD_LOG,
        "max_iterations": str(config.ai_resolve.max_iterations),
        "label": config.ai_resolve.label,
    }

    def _replace(match: re.Match[str]) -> str:
        key = match.group(1)
        return placeholders.get(key, match.group(0))

    return re.sub(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", _replace, template)


# ---------------------------------------------------------------------------
# Claude invocation
# ---------------------------------------------------------------------------


def _build_claude_argv(config: Config, prompt: str) -> list[str]:
    cmd = [
        config.ai_resolve.command,
        "-p", prompt,
        "--output-format", "stream-json",
        "--verbose",
    ]
    if config.ai_resolve.allowed_tools:
        cmd += ["--allowedTools", ",".join(config.ai_resolve.allowed_tools)]
    cmd += list(config.ai_resolve.extra_args)
    return cmd


def _fmt_elapsed(seconds: float) -> str:
    s = int(seconds)
    if s < 60:
        return f"{s}s"
    if s < 3600:
        return f"{s // 60}m{s % 60:02d}s"
    return f"{s // 3600}h{(s % 3600) // 60:02d}m"


def _truncate(text: str, n: int = 120) -> str:
    text = text.strip().replace("\n", " ⏎ ")
    return text if len(text) <= n else text[: n - 1] + "…"


def _render_event(line: str, start: float) -> str | None:
    """Turn one stream-json event into a human-readable status line.

    Returns ``None`` when the event has nothing user-visible to report.
    """
    try:
        ev = json.loads(line)
    except json.JSONDecodeError:
        stripped = line.strip()
        if not stripped:
            return None
        return f"[dim]│[/dim] {stripped}"

    elapsed = _fmt_elapsed(time.monotonic() - start)
    etype = ev.get("type")

    if etype == "system":
        sub = ev.get("subtype", "")
        model = ev.get("model") or ""
        if sub == "init":
            return f"[dim]│ [{elapsed}][/dim] [magenta]session start[/magenta] {model}".rstrip()
        return None

    if etype == "assistant":
        msg = ev.get("message") or {}
        parts = []
        for block in msg.get("content") or []:
            btype = block.get("type")
            if btype == "text":
                txt = _truncate(block.get("text", ""))
                if txt:
                    parts.append(f"[dim]│ [{elapsed}][/dim] [cyan]💬[/cyan] {txt}")
            elif btype == "thinking":
                txt = _truncate(block.get("thinking", ""), 80)
                if txt:
                    parts.append(f"[dim]│ [{elapsed}] 🧠 {txt}[/dim]")
            elif btype == "tool_use":
                name = block.get("name", "tool")
                inp = block.get("input") or {}
                summary = ""
                if name == "Bash":
                    summary = _truncate(str(inp.get("command", "")), 100)
                elif name in ("Read", "Write", "Edit"):
                    summary = str(inp.get("file_path") or inp.get("path") or "")
                elif name == "Glob":
                    summary = str(inp.get("pattern") or inp.get("glob_pattern") or "")
                elif name == "Grep":
                    summary = _truncate(str(inp.get("pattern", "")), 80)
                else:
                    keys = ", ".join(list(inp)[:3])
                    summary = f"({keys})" if keys else ""
                line_str = f"[dim]│ [{elapsed}][/dim] [yellow]🔧 {name}[/yellow]"
                if summary:
                    line_str += f" {summary}"
                parts.append(line_str)
        return "\n".join(parts) if parts else None

    if etype == "user":
        msg = ev.get("message") or {}
        for block in msg.get("content") or []:
            if block.get("type") == "tool_result":
                content = block.get("content")
                if isinstance(content, list):
                    text = " ".join(
                        c.get("text", "") for c in content if isinstance(c, dict)
                    )
                else:
                    text = str(content or "")
                is_err = block.get("is_error")
                marker = "[red]✗[/red]" if is_err else "[green]✓[/green]"
                summary = _truncate(text, 100)
                if not summary:
                    return None
                return f"[dim]│ [{elapsed}][/dim] {marker} [dim]{summary}[/dim]"
        return None

    if etype == "result":
        sub = ev.get("subtype", "")
        cost = ev.get("total_cost_usd")
        turns = ev.get("num_turns")
        bits = [f"result={sub}"]
        if turns is not None:
            bits.append(f"turns={turns}")
        if cost is not None:
            bits.append(f"cost=${cost:.3f}")
        return f"[dim]│ [{elapsed}] {' '.join(bits)}[/dim]"

    return None


def _kill_proc_tree(proc: subprocess.Popen) -> None:
    """SIGTERM (then SIGKILL) the entire process group of ``proc``.

    Claude spawns child tools (ninja, gcc, gh, …); without targeting the
    whole group those survive after we kill claude itself. ``proc`` is
    started with ``start_new_session=True`` so it owns its own process
    group whose pgid equals the child pid.
    """
    if proc.poll() is not None:
        return
    try:
        pgid = os.getpgid(proc.pid)
    except (ProcessLookupError, OSError):
        return
    try:
        os.killpg(pgid, signal.SIGTERM)
    except (ProcessLookupError, OSError):
        pass
    try:
        proc.wait(timeout=5)
        return
    except subprocess.TimeoutExpired:
        pass
    try:
        os.killpg(pgid, signal.SIGKILL)
    except (ProcessLookupError, OSError):
        pass
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass


def _spawn_claude(
    argv: list[str], repo_path: Path, timeout: int,
) -> tuple[int, str, bool]:
    """Run claude as a subprocess, streaming stdout/stderr to the console.

    Parses Claude's stream-json events and pretty-prints each tool call,
    message, and tool result. Emits a heartbeat when claude is quiet so
    the user can tell it's still working. Ctrl-C kills the whole claude
    process group (claude + ninja + whatever else it spawned) and
    re-raises ``KeyboardInterrupt``.

    Returns (exit_code, combined_output, timed_out).
    """
    console.print(
        f"    [dim]$ {shlex.join(argv[:2])} <prompt…> "
        f"{shlex.join(argv[3:])}[/dim]"
    )
    console.print("    [dim](press Ctrl-C to abort claude)[/dim]")

    env = os.environ.copy()

    # start_new_session=True puts claude in its own process group so:
    #   1. it does NOT receive the terminal's Ctrl-C (we control it),
    #   2. we can kill the entire tree (claude + nested tools) at once.
    proc = subprocess.Popen(
        argv,
        cwd=repo_path,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        start_new_session=True,
    )

    collected: list[str] = []
    start = time.monotonic()
    last_output = start
    timed_out = False
    interrupted = False
    stop_heartbeat = threading.Event()

    def _heartbeat() -> None:
        idle_threshold = 30.0
        while not stop_heartbeat.wait(15.0):
            idle = time.monotonic() - last_output
            if idle >= idle_threshold:
                console.print(
                    f"    [dim]│ [{_fmt_elapsed(time.monotonic() - start)}] "
                    f"…still working (idle {int(idle)}s)[/dim]"
                )

    hb = threading.Thread(target=_heartbeat, daemon=True)
    hb.start()

    try:
        assert proc.stdout is not None
        while True:
            if (time.monotonic() - start) > timeout:
                timed_out = True
                break
            try:
                line = proc.stdout.readline()
            except KeyboardInterrupt:
                interrupted = True
                break
            if not line:
                if proc.poll() is not None:
                    break
                continue
            collected.append(line)
            last_output = time.monotonic()
            rendered = _render_event(line, start)
            if rendered:
                console.print(f"    {rendered}")
    except KeyboardInterrupt:
        interrupted = True
    except Exception as exc:
        collected.append(f"[runner] error streaming claude output: {exc}\n")
    finally:
        stop_heartbeat.set()
        if proc.poll() is None:
            reason = (
                "interrupted by user"
                if interrupted
                else f"timed out after {timeout}s"
                if timed_out
                else "stream ended; cleaning up"
            )
            console.print(
                f"    [yellow]✗ killing claude ({reason})…[/yellow]"
            )
            _kill_proc_tree(proc)

    if interrupted:
        raise KeyboardInterrupt

    exit_code = proc.returncode if proc.returncode is not None else -1
    return exit_code, "".join(collected), timed_out


# ---------------------------------------------------------------------------
# Post-condition verification
# ---------------------------------------------------------------------------


def _extract_assistant_text(output: str) -> str:
    """Pull all assistant text out of a stream-json transcript.

    Falls back to the raw output when nothing parses as JSON.
    """
    chunks: list[str] = []
    parsed_any = False
    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            chunks.append(line)
            continue
        parsed_any = True
        if ev.get("type") == "assistant":
            for block in (ev.get("message") or {}).get("content") or []:
                if block.get("type") == "text":
                    chunks.append(block.get("text", ""))
        elif ev.get("type") == "result":
            res = ev.get("result")
            if isinstance(res, str):
                chunks.append(res)
    if not parsed_any:
        return output
    return "\n".join(chunks)


# Heuristics for transient Anthropic streaming-API failures that abort
# the turn before Claude can do any real work. We retry on these; we do
# NOT retry on real resolver errors (build failed, UNRESOLVED, etc.).
_TRANSIENT_API_ERROR_RES = [
    re.compile(r"API Error:\s*Stream idle timeout", re.IGNORECASE),
    re.compile(r"API Error:\s*Overloaded", re.IGNORECASE),
    re.compile(r"API Error:\s*5\d\d", re.IGNORECASE),
    re.compile(r"API Error:\s*Connection (?:reset|closed)", re.IGNORECASE),
    re.compile(r"API Error:\s*Request timed out", re.IGNORECASE),
    re.compile(r"API Error:\s*ECONNRESET", re.IGNORECASE),
    re.compile(r"API Error:\s*fetch failed", re.IGNORECASE),
    re.compile(r"partial response received", re.IGNORECASE),
]


def _find_transient_api_error(output: str) -> str | None:
    """Return a short human-readable reason if the turn was aborted by a
    transient Anthropic API error, else ``None``.

    We look both in raw lines and in the assistant text extracted from
    the stream-json transcript.
    """
    assistant = _extract_assistant_text(output)
    for haystack in (assistant, output):
        for pat in _TRANSIENT_API_ERROR_RES:
            m = pat.search(haystack)
            if m:
                return m.group(0)
    return None


def _count_iterations(output: str) -> int | None:
    """Best-effort: count how many build attempts Claude ran.

    Looks for patterns in its own narration. Returns None when unknown.
    """
    text = _extract_assistant_text(output)
    patterns = [
        r"build attempt[s]?:?\s*(\d+)",
        r"iteration\s*(\d+)\s*/\s*\d+",
    ]
    best: int | None = None
    for pat in patterns:
        for m in re.finditer(pat, text, re.IGNORECASE):
            try:
                n = int(m.group(1))
            except ValueError:
                continue
            best = n if best is None else max(best, n)
    return best


def _verify_postconditions(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> tuple[bool, str | None, str | None]:
    """Step-mode check: cherry-pick fully concluded, tree clean, HEAD moved.

    RelEasy itself owns push / PR / label, so we only verify Claude's
    local-repo invariants:

    - no cherry-pick / merge / rebase still in progress,
    - working tree is clean (no unstaged conflict-resolution leftovers),
    - the port branch advanced past ``ctx.start_sha`` (i.e. at least one
      commit was actually made).

    Returns ``(ok, new_head_sha, error_message)``.
    """
    if is_operation_in_progress(repo_path):
        return False, None, (
            "cherry-pick/merge/rebase still in progress after claude exited"
        )

    porc = run_git(["status", "--porcelain"], repo_path, check=False)
    if porc.stdout.strip():
        files = ", ".join(
            line[3:] for line in porc.stdout.splitlines()[:5]
        )
        return False, None, f"working tree not clean: {files}"

    head = run_git(["rev-parse", "--verify", "HEAD"], repo_path, check=False)
    if head.returncode != 0:
        return False, None, "could not read HEAD"
    new_head = head.stdout.strip()

    if ctx.start_sha and new_head == ctx.start_sha:
        return False, new_head, (
            "no new commits — cherry-pick was not concluded"
        )

    return True, new_head, None


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def resolve_with_claude(
    config: Config, repo_path: Path, ctx: AIResolveContext,
) -> AIResolveResult:
    """Render the prompt, run claude, and verify post-conditions."""
    if shutil.which(config.ai_resolve.command) is None:
        return AIResolveResult(
            success=False,
            error=f"'{config.ai_resolve.command}' not found on PATH",
        )

    try:
        _write_build_script(repo_path, config.ai_resolve.build_command)
    except OSError as exc:
        return AIResolveResult(
            success=False, error=f"could not write build wrapper: {exc}",
        )

    try:
        prompt = _render_prompt(config, repo_path, ctx)
    except FileNotFoundError as exc:
        return AIResolveResult(success=False, error=str(exc))

    argv = _build_claude_argv(config, prompt)

    console.print(
        f"    [magenta]\U0001f916 invoking {config.ai_resolve.command} "
        f"(timeout {config.ai_resolve.timeout_seconds}s, "
        f"max {config.ai_resolve.max_iterations} build attempts, "
        f"up to {config.ai_resolve.api_retries} API-error retries)[/magenta]"
    )

    max_attempts = max(1, config.ai_resolve.api_retries + 1)
    backoff = max(0, config.ai_resolve.api_retry_backoff_seconds)

    last_exit_code = -1
    last_output = ""
    last_timed_out = False

    for attempt in range(1, max_attempts + 1):
        if attempt > 1:
            console.print(
                f"    [yellow]↻ retrying claude after transient API error "
                f"(attempt {attempt}/{max_attempts}, sleeping {backoff}s)"
                f"[/yellow]"
            )
            try:
                time.sleep(backoff)
            except KeyboardInterrupt:
                raise

        exit_code, output, timed_out = _spawn_claude(
            argv, repo_path, config.ai_resolve.timeout_seconds,
        )
        last_exit_code, last_output, last_timed_out = exit_code, output, timed_out

        if timed_out:
            break

        transient = _find_transient_api_error(output)
        if transient and exit_code != 0 and attempt < max_attempts:
            console.print(
                f"    [yellow]⚠ transient API error: {transient}"
                f" — will retry[/yellow]"
            )
            continue

        break

    exit_code = last_exit_code
    output = last_output
    timed_out = last_timed_out

    iterations = _count_iterations(output)
    assistant_text = _extract_assistant_text(output)

    if timed_out:
        return AIResolveResult(
            success=False, timed_out=True, iterations=iterations,
            error=f"claude timed out after {config.ai_resolve.timeout_seconds}s",
        )

    tail_lines = assistant_text.strip().splitlines()[-40:] if assistant_text.strip() else []
    tail_str = "\n".join(tail_lines)
    if any(line.strip() == "UNRESOLVED" for line in tail_lines):
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported UNRESOLVED",
        )
    if any(line.strip() == "BUILD FAILED" for line in tail_lines):
        return AIResolveResult(
            success=False, iterations=iterations,
            error="claude reported BUILD FAILED",
        )

    if exit_code != 0:
        transient = _find_transient_api_error(output)
        suffix = (
            f" (transient API error after {max_attempts} attempt(s): {transient})"
            if transient
            else ""
        )
        return AIResolveResult(
            success=False, iterations=iterations,
            error=f"claude exited with code {exit_code}{suffix}\n{tail_str}",
        )

    ok, new_head, err = _verify_postconditions(config, repo_path, ctx)
    if not ok:
        return AIResolveResult(
            success=False, iterations=iterations, new_head=new_head, error=err,
        )

    return AIResolveResult(
        success=True, iterations=iterations, new_head=new_head, error=err,
    )
